name: "Build and Release Plugin"

on:
  push:
    tags:
      - "v*.*.*"  # Triggers on version tags like v1.0.0, v1.2.3, etc.
  release:
    types: [created]
  workflow_dispatch:  # Allow manual trigger

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build extension
        run: npm run build
        env:
          NODE_NO_WARNINGS: 1
          PLASMO_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.PLASMO_PUBLIC_CLERK_PUBLISHABLE_KEY }}
          PLASMO_PUBLIC_CLERK_SYNC_HOST: ${{ secrets.PLASMO_PUBLIC_CLERK_SYNC_HOST }}
          CLERK_FRONTEND_API: ${{ secrets.CLERK_FRONTEND_API }}
          PLASMO_PUBLIC_API_URL: ${{ secrets.PLASMO_PUBLIC_API_URL }}
          PLASMO_PUBLIC_DATA_IO_URL: ${{ secrets.PLASMO_PUBLIC_DATA_IO_URL }}
          CRX_PUBLIC_KEY: ${{ secrets.CRX_PUBLIC_KEY }}
          
      - name: Package extension
        run: npm run package
        env:
          NODE_NO_WARNINGS: 1
          PLASMO_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.PLASMO_PUBLIC_CLERK_PUBLISHABLE_KEY }}
          PLASMO_PUBLIC_CLERK_SYNC_HOST: ${{ secrets.PLASMO_PUBLIC_CLERK_SYNC_HOST }}
          CLERK_FRONTEND_API: ${{ secrets.CLERK_FRONTEND_API }}
          PLASMO_PUBLIC_API_URL: ${{ secrets.PLASMO_PUBLIC_API_URL }}
          PLASMO_PUBLIC_DATA_IO_URL: ${{ secrets.PLASMO_PUBLIC_DATA_IO_URL }}
          CRX_PUBLIC_KEY: ${{ secrets.CRX_PUBLIC_KEY }}
          
      - name: Debug build output
        run: |
          echo "Build directory contents:"
          ls -la build/ || echo "Build directory not found"
          echo "Root directory contents:"
          ls -la
          echo "Looking for zip files:"
          find . -name "*.zip" -type f || echo "No zip files found"
          
      - name: Get version from package.json
        id: package-version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Extension version: $VERSION"
          
      - name: Rename zip file with version and create latest
        run: |
          # First try the expected location
          if [ -f "build/chrome-mv3-prod.zip" ]; then
            echo "Found zip file at build/chrome-mv3-prod.zip"
            # Create versioned file
            cp build/chrome-mv3-prod.zip build/cogix-browser-plugin-chrome-v${{ steps.package-version.outputs.version }}.zip
            # Create latest file (permanent URL)
            mv build/chrome-mv3-prod.zip build/cogix-browser-plugin-latest.zip
          else
            echo "Looking for zip files in alternative locations..."
            # Look for any zip file in build directory
            ZIP_FILE=$(find build -name "*.zip" -type f | head -1)
            if [ -n "$ZIP_FILE" ]; then
              echo "Found zip file at: $ZIP_FILE"
              # Create versioned file
              cp "$ZIP_FILE" build/cogix-browser-plugin-chrome-v${{ steps.package-version.outputs.version }}.zip
              # Create latest file (permanent URL)
              mv "$ZIP_FILE" build/cogix-browser-plugin-latest.zip
            else
              echo "No zip file found! Creating one manually..."
              cd build/chrome-mv3-prod && zip -r ../cogix-browser-plugin-chrome-v${{ steps.package-version.outputs.version }}.zip .
              cd build/chrome-mv3-prod && zip -r ../cogix-browser-plugin-latest.zip .
            fi
          fi
          
      - name: Verify build output
        run: |
          echo "Build directory contents:"
          ls -la build/
          echo "Final zip file check:"
          ls -la build/cogix-browser-plugin-chrome-v${{ steps.package-version.outputs.version }}.zip || echo "Final zip file not found!"
          echo "Extension files:"
          if [ -f "build/cogix-browser-plugin-chrome-v${{ steps.package-version.outputs.version }}.zip" ]; then
            unzip -l build/cogix-browser-plugin-chrome-v${{ steps.package-version.outputs.version }}.zip
            echo "Zip file size:"
            du -h build/cogix-browser-plugin-chrome-v${{ steps.package-version.outputs.version }}.zip
          else
            echo "Cannot list zip contents - file not found"
          fi
          
      - name: Ensure zip file exists for release
        run: |
          ZIP_FILE="build/cogix-browser-plugin-chrome-v${{ steps.package-version.outputs.version }}.zip"
          if [ ! -f "$ZIP_FILE" ]; then
            echo "ERROR: Zip file not found at $ZIP_FILE"
            echo "Available files in build directory:"
            ls -la build/
            echo "Creating zip file as last resort..."
            if [ -d "build/chrome-mv3-prod" ]; then
              cd build/chrome-mv3-prod && zip -r "../cogix-browser-plugin-chrome-v${{ steps.package-version.outputs.version }}.zip" .
              cd ../..
              echo "Zip file created successfully"
            else
              echo "ERROR: No build directory found!"
              exit 1
            fi
          else
            echo "Zip file exists: $ZIP_FILE"
          fi
          
      - name: Create Release (if triggered by tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/cogix-browser-plugin-chrome-v${{ steps.package-version.outputs.version }}.zip
            build/cogix-browser-plugin-latest.zip
          name: "Cogix Browser Plugin Chrome v${{ steps.package-version.outputs.version }}"
          body: |
            ## Cogix Browser Plugin Chrome v${{ steps.package-version.outputs.version }}
            
            ### Installation Instructions
            
            1. Download the `cogix-browser-plugin-chrome-v${{ steps.package-version.outputs.version }}.zip` file below
            2. Extract the ZIP file to a local folder
            3. Open Chrome and go to `chrome://extensions/`
            4. Enable "Developer mode" in the top right
            5. Click "Load unpacked" and select the extracted folder
            6. The Cogix Browser Plugin will be installed and ready to use
            
            ### What's New
            
            - Eye tracking functionality with real-time calibration
            - Screen recording capabilities
            - Event capture and data collection
            - Seamless integration with Cogix platform
            - Dedicated SDK download and management interface
            
            ### System Requirements
            
            - Chrome browser (latest version recommended)
            - Windows 10 or later (for eye tracking SDK)
            - Compatible eye tracking hardware
            
            ### Support
            
            For support and documentation, visit [cogix.app](https://cogix.app)
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Verify release was created
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "Release creation completed"
          echo "Checking if zip file still exists:"
          ls -la build/cogix-browser-plugin-chrome-v${{ steps.package-version.outputs.version }}.zip || echo "Zip file not found after release"
          echo "GitHub release should now contain the extension file"
          
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: cogix-browser-plugin-chrome-v${{ steps.package-version.outputs.version }}
          path: build/cogix-browser-plugin-chrome-v${{ steps.package-version.outputs.version }}.zip
          retention-days: 90
          
      - name: Generate build summary
        run: |
          echo "## Build Summary" >> $GITHUB_STEP_SUMMARY
          echo "- **Version**: ${{ steps.package-version.outputs.version }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Build Status**: ✅ Success" >> $GITHUB_STEP_SUMMARY
          echo "- **Artifact**: cogix-browser-plugin-chrome-v${{ steps.package-version.outputs.version }}.zip" >> $GITHUB_STEP_SUMMARY
          echo "- **Size**: $(du -h build/cogix-browser-plugin-chrome-v${{ steps.package-version.outputs.version }}.zip | cut -f1)" >> $GITHUB_STEP_SUMMARY
          echo "- **Commit**: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            echo "- **Release**: Created GitHub release" >> $GITHUB_STEP_SUMMARY
          else
            echo "- **Release**: Artifact only (no GitHub release)" >> $GITHUB_STEP_SUMMARY
          fi
